# Common rules for all tests.
#
# The tests only have to define the following variables and rules:
#
# - ROOT: the root of the source
# - PDFS: the list of Pdf files to be generated.
# - For each of the Pdf files, a rule that generates either a .deps file or a
#   .clusters file (there is a rule that automatically generates a clusted .deps
#   from a .clusters if required).

# Define new file types.
.SUFFIXES: .log .deps .dot .pdf .clusters

# Allow including this file from anywhere.
## (only works with GNU make-3.81)
##.SECONDEXPANSION:

# Do not delete intermediate dot files from chained implicit rules.
.PRECIOUS: %.log %.deps %.dot %.clusters

OS = $(shell uname)
ifeq ($(OS),Darwin)
   PSTOPDF=pstopdf -i -o
else
   PSTOPDF=ps2pdf -
endif

FOOD_FLAGS= --internal-only


all: $(PDFS)

# Generate the raw list of dependencies for the entire codebase.
raw.deps: $(ROOT)
	sfood -v $(FOOD_FLAGS) $(ROOT) 2>&1 > $@ | tee raw.log

# Implicit rules.
.deps.dot:
	cat $< | sfood-graph -p > $@

.dot.pdf:
	cat $< | dot -Tps | $(PSTOPDF) $@

# Implicit rule to convert the raw.deps file simply from the existence of a
# .clusters file.
%.deps: %.clusters raw.deps
	cat raw.deps | sfood-cluster -f $< > $@

# Clean everything but the costly raw dependencies.
clean:
	ls -1 *.deps | grep -v ^raw.deps | xargs rm -f
	rm -f *.dot *.ps *.pdf *.clusters

# Really clean everything.
realclean: clean
	rm -f raw.deps raw.log

