# Run the automated tests.

.SUFFIXES: .py .deps .log .expect


all: depends


# Version of Python to use for the tests.
PYTHON = python2.5

BINDIR = ../../bin
SFOOD = $(PYTHON) $(BINDIR)/sfood


# Tests comparing actual output with expected output.
TARGETS =					\
	simple/stdlib				\
	simple/invalid				\
	simple/notfound				\
	project/foo_import			\
	project/foo_from

TARGETS_UNUSED =				\
	simple/unused


depends: $(TARGETS) $(TARGETS_UNUSED)

$(TARGETS):
	@echo "------ Testing $@"
	@$(SFOOD) $@.py > $@.deps 2> $@.log
	@diff $@.expect $@.deps

$(TARGETS_UNUSED):
	@echo "------ Testing $@"
	@$(SFOOD) --ignore-unused $@.py > $@.deps 2> $@.log
	@diff $@.expect $@.deps






clean:
	rm -f *.deps *.log {project,simple}/*.{deps,log}

