# Run the automated tests.

.SUFFIXES: .py .deps .log .expect .roots


all: roots depends functional


# Version of Python to use for the tests.
PYTHON = python2.5

BINDIR = ../../bin
SFOOD = $(PYTHON) $(BINDIR)/sfood


# Tests comparing actual output with expected output.
TARGETS =					\
	simple/stdlib				\
	simple/invalid				\
	simple/notfound				\
	project/foo_import			\
	project/foo_from

TARGETS_UNUSED =				\
	simple/unused


depends: $(TARGETS) $(TARGETS_UNUSED) $(CHECK)

$(TARGETS):
	@echo "------ Testing $@"
	@$(SFOOD) $@.py > $@.deps 2> $@.log
	@diff $@.expect $@.deps

$(TARGETS_UNUSED):
	@echo "------ Testing $@"
	@$(SFOOD) --ignore-unused $@.py > $@.deps 2> $@.log
	@diff $@.expect $@.deps


# Testing the root identification, against expect files.
TESTROOT = $(PWD)
RDIRS := $(shell find roots -type d | grep -v /.svn)
REXPECTS := $(RDIRS:=/.expect)
ROOTS = $(RDIRS:=/.roots)





clean:
	rm -f *.deps *.log {project,simple}/*.{deps,log}
	rm -f $(ROOTS)

