# Run the automated tests.

.SUFFIXES: .py .deps .log .expect


all: 


# Version of Python to use for the tests.
PYTHON = python2.5

BINDIR = ../../bin
SFOOD = $(PYTHON) $(BINDIR)/sfood






clean:
	rm -f *.deps *.log {project,simple}/*.{deps,log}

