# Graph the dependencies for Matplotlib.

ROOT=$(HOME)/src/matplotlib/matplotlib/build/lib.linux-i686-2.4

PDFS =						\
	matplotlib.pdf

include ../Makefile.rules


# Handmade clusters list.
matplotlib.clusters: clusters
	cp $< $@

