# Graph the dependencies for Zope-3.

ROOT=$(HOME)/src/Zope-3.3.1

PDFS =						\
	zope.pdf

include ../Makefile.rules

# # Cluster at least the first level of subdirectories.
# twisted.clusters:
# 	(cd $(ROOT)/..; ls -1d twisted/* | grep -v \\. > $(shell pwd)/$@)

## FIXME: unfinished
