# Graph the dependencies for the David Mertz' Gnosis.

ROOT=$(HOME)/src/Gnosis_Utils-1.2.1

PDFS =						\
	gnosis.pdf

include ../Makefile.rules

# Hand-coded clusters file.
gnosis.clusters: clusters
	cp clusters gnosis.clusters

