# Graph the dependencies for the David Mertz' Gnosis.
include ../Makefile.common

ROOT=$(HOME)/src/Gnosis_Utils-1.2.1

PDFS =						\
	gnosis.pdf

# Hand-coded clusters file.
gnosis.clusters: clusters
	cp clusters gnosis.clusters

